package com.example.smetracker.data.remote.model

// Firestore path: businesses/{businessId}/members/{phoneNumberE164}
// Document ID is the member's own E.164 phone number, not an autogenerated ID,
// so it can be looked up directly without a query.
data class BusinessMember(
    val phone: String = "",
    val name: String = "",
    val role: MemberRole = MemberRole.WORKER,
    val addedAt: Long = System.currentTimeMillis(),
    // Phone number of the owner who added this member — an audit trail,
    // and useful if a business ever has more than one owner-level account later.
    val addedBy: String = ""
)